[package]
name = "my-redis"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.39.0", features = ["full"] }
mini-redis = "0.4.0"

[[example]]
name="hello-redis"
path="examples/hello-redis.rs"